### ISSUE TITLE
Small caps

### ISSUE THREAD

**Issue by ctrlcctrlv** [indestructible-type/Besley#14]
I like this font and want small caps :)

**Comment by ctrlcctrlv** [comment]
Oh, you seem to use a similar build system to me (FontForge+fontmake), so maybe I could add them…

**Comment by ctrlcctrlv** [comment]
I'm trying to do this but am not sure of the files to edit.

`sources/fontforge` looks like:

```
.
├── Book.sfd
├── Fatface.sfd
└── FontForge Files
    ├── Bold
    │   ├── Besley-BoldItalicROUND.sfd
    │   ├── Besley-BoldItalic.sfd
    │   ├── Besley-BoldROUND.sfd
    │   └── Besley-Bold.sfd
    ├── Book
    │   ├── Besley-BookItalic ROUND.sfd
    │   ├── Besley-BookItalic.sfd
    │   ├── Besley-Book ROUND.sfd
    │   └── Besley-Book.sfd
    ├── Fatface
    │   ├── Besley-FatfaceItalic ROUND.sfd
    │   ├── Besley-FatfaceItalic.sfd
    │   ├── Besley-Fatface ROUND.sfd
    │   └── Besley-Fatface.sfd
    └── Medium
        ├── Besley-MediumItalicROUND.sfd
        ├── Besley-MediumItalic.sfd
        ├── Besley-MediumROUND.sfd
        └── Besley-Medium.sfd
```

However there are only four UFO's:

```tree
UFO
├── Besley-BlackItalic.ufo
├── Besley-Black.ufo
├── Besley-Italic.ufo
└── Besley-Regular.ufo
```

How do these files relate? Should I just try to edit the UFO's and splice in smallcaps glyphs? That seems like it would work, but what's the process for generating these UFO's in the first place?

**Comment by EwonRael** [comment]
hey

so I kind of consider the ufo sources the official sources because those are universal and fontforge files are program exclusive so I didn't bother to maintain the fontforge sources in the repo just the UFO files.

I went ahead and updated the fontforge files to reflect the actual reality of the project. When I first started this project I was drawing all the weights from scratch but when I decided to make it a variable font I redrew everything so it's interpolatable and now just pull from four sources.

It should be much clearer now what's actually relevant to the project in its current state. Good chance I have an incompatible anchor here and there that I fixed in the UFO version.

thanks for your help and interest in this project.
