### ISSUE TITLE
Add Æ and correct Ø to small caps

### ISSUE THREAD

**Issue by sigurdhasle** [indestructible-type/Besley#32]
Wow! You fixed it – NOT! The small caps still need a bit of work. The æ's are _still_ just lowercase instead of small uppercase letters. The ø's should be the same shape and size as the o's, but with a slash through it. The slash should go throught the middle of the ring (the two crescents should be the same size). Slurv!

![image](https://user-images.githubusercontent.com/47284316/211532562-49f80d77-e645-4df3-95c5-48ccf92cb022.png)

**Comment by ctrlcctrlv** [comment]
Stop being such a rude asshole to Owen.

He did fix it.

![image](https://user-images.githubusercontent.com/838783/211534045-05362e00-1bf2-45fe-bca0-40b0fc4e086f.png)

It's possible he didn't update the TTF's distributed, or for some other reason, you're still using an old font. Making a duplicate issue instead of replying in the existing one with something nicer like "it still doesn't work for me, any idea why?" will get you a lot more traction.

Closed.

**Comment by sigurdhasle** [comment]
I am sorry if you consider me a rude asshole. I opened a new issue because I was not aware that I could comment in a closed one. I am just frustrated that I cannot use the small caps.
I have downloaded and installed the files again today. The small caps Æ still looks like a lowercase æ.
